In this lecture we'll talk about modules (not the ones you write by yourself for now) and discuss some common use examples.

General remarks:

**never do `from numpy inport *`**

**never do `%pylab inline`**

This can only be done when you really need to save screen space and typing time (like is done in your other lectures, but never in real life. Remember `using namespace std`? This is even worse.

**Exercise0:** go through any 2 lectures of numerical analysis and fix the notebooks to use all the names properly.

### **Standard Library**

[the whole library docs](https://docs.python.org/3/library/)

[math module docs](https://docs.python.org/3/library/math.html)

[itertools docs](https://docs.python.org/3/library/itertools.html?highlight=itertools#module-itertools)

In [3]:
import math

In [4]:
math.sin(math.pi/2)

1.0

In [5]:
math.sqrt(2)

1.4142135623730951

In [6]:
import itertools as it

In [7]:
permut = it.permutations([1,2,3])
comb = it.combinations([1,2,3,4,5],3) 
pr = it.product([1,2,3],[2,3,4])

In [8]:
print(*permut)

(1, 2, 3) (1, 3, 2) (2, 1, 3) (2, 3, 1) (3, 1, 2) (3, 2, 1)


In [9]:
type(permut)

itertools.permutations

In [10]:
print(*comb)

(1, 2, 3) (1, 2, 4) (1, 2, 5) (1, 3, 4) (1, 3, 5) (1, 4, 5) (2, 3, 4) (2, 3, 5) (2, 4, 5) (3, 4, 5)


In [11]:
print(*pr)

(1, 2) (1, 3) (1, 4) (2, 2) (2, 3) (2, 4) (3, 2) (3, 3) (3, 4)


### **Numpy**

From the docs:

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

[documentation](https://numpy.org/doc/stable/user/whatisnumpy.html)


Numpy is mostly used for manipulations on arrays. It's usually imported as "np". 

In [14]:
import numpy as np

Let's start with the different ways of arrays creations:

In [15]:
arr1 = np.array([1,2,3,4,5])                    # From a list (works with list comprehensions too)
print(arr1)             
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [16]:
arr2 = np.array([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


You can create an array with zeros, ones, or leave it uninitialized

In [17]:
arr3 = np.zeros((3,4), dtype='int')            
arr4 = np.ones((3,4), dtype='float')
arr5=np.empty(10)
print(arr3)
print(arr4)
print(arr5)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[nan  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [18]:
arr6 = np.full((3,5), 7.77)       # fill in the array with 1 number
arr7 = np.arange(1,100,17)        # just like "range"
arr8 = np.linspace(0,1,27)        # 27 values linearly spaced from 0 to 1
arr9 = np.eye(3)      #identity
print(arr6)
print(arr7)
print(arr8)
print(arr9)

[[7.77 7.77 7.77 7.77 7.77]
 [7.77 7.77 7.77 7.77 7.77]
 [7.77 7.77 7.77 7.77 7.77]]
[ 1 18 35 52 69 86]
[0.         0.03846154 0.07692308 0.11538462 0.15384615 0.19230769
 0.23076923 0.26923077 0.30769231 0.34615385 0.38461538 0.42307692
 0.46153846 0.5        0.53846154 0.57692308 0.61538462 0.65384615
 0.69230769 0.73076923 0.76923077 0.80769231 0.84615385 0.88461538
 0.92307692 0.96153846 1.        ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
arr10=np.ones_like(arr6)
print(arr10)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


You can also create random arrays:

In [20]:
arr11 = np.random.random((3,5))    # 3x5 Random numbers matrix with entries between 0-1
arr12 = np.random.normal(0,5,(3,4))  # 3x4 Random numbers normal distributed with mean 0 and standard dev 5
print(arr11)
print(arr12)

[[0.08527895 0.8505798  0.64413216 0.16314731 0.5023572 ]
 [0.92289655 0.1315855  0.97219931 0.84382526 0.50876496]
 [0.49269566 0.13554956 0.05679765 0.48226802 0.80190312]]
[[ 1.06097561 -6.03102285 -1.21623276  0.34084383]
 [-7.07615655  6.99086035 -6.80198569  6.96071633]
 [ 2.25004934 -1.11133826  3.3257856   1.12711797]]


#### **Element-wise calculations:**

In [21]:
#standard math operations:
A = np.linspace(1,10,10)
B = np.linspace(1,10,10) #it will complain if sizes do not match
print(A+B)
print(A-B)
print(A*B)
print(A/B)
print(A//B)
print(A**B)
print(A%B)


[ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[  1.   4.   9.  16.  25.  36.  49.  64.  81. 100.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1.00000000e+00 4.00000000e+00 2.70000000e+01 2.56000000e+02
 3.12500000e+03 4.66560000e+04 8.23543000e+05 1.67772160e+07
 3.87420489e+08 1.00000000e+10]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
arr=np.linspace(0.1,1,10)
print(abs(arr))
print(np.cos(arr))
print(np.arccos(arr))
print(np.exp(arr))
print(np.log(abs(arr)))
print(np.reciprocal(arr))

[0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[0.99500417 0.98006658 0.95533649 0.92106099 0.87758256 0.82533561
 0.76484219 0.69670671 0.62160997 0.54030231]
[1.47062891 1.36943841 1.26610367 1.15927948 1.04719755 0.92729522
 0.79539883 0.64350111 0.45102681 0.        ]
[1.10517092 1.22140276 1.34985881 1.4918247  1.64872127 1.8221188
 2.01375271 2.22554093 2.45960311 2.71828183]
[-2.30258509 -1.60943791 -1.2039728  -0.91629073 -0.69314718 -0.51082562
 -0.35667494 -0.22314355 -0.10536052  0.        ]
[10.          5.          3.33333333  2.5         2.          1.66666667
  1.42857143  1.25        1.11111111  1.        ]


#### **Joining, splitting, shaping**

In [23]:
#for joining arrays you can use concatinate
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(np.concatenate([arr1,arr2]))


[1 2 3 4 5 6 7 8]


In [24]:
#you can reshape the arrays, it will complain if dimensions do not allow for that
A = arr1.reshape(2,2)
B = arr2.reshape(2,2)
print(np.concatenate([A,B]))
print(np.concatenate([A,B],axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [25]:
#you can "stack" arrays horizontally or vertically
vect1 = np.array([1,2,3])
vect2 = np.array([[4,5,6],[7,8,9]])
print(vect1,np.shape(vect1))
print(vect2,np.shape(vect2))
print(np.vstack([vect1,vect2]))
print(np.hstack([vect1.reshape(3,1),vect2.T]))

[1 2 3] (3,)
[[4 5 6]
 [7 8 9]] (2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [26]:
#splitting the arrays
A = np.arange(20).reshape(4,5)
print(A)
B,C = np.split(A,2)
print("B=",B)
print("C=",C)
B,C = np.split(A,[3],axis=1) #split vertically
print(B)
print(C)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
B= [[0 1 2 3 4]
 [5 6 7 8 9]]
C= [[10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]
 [15 16 17]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]]


#### **Element access**

In [27]:
A = np.array([range(i,i+5) for i in [1,6,11,16,21]])
print(A,'\n')
print(A[1,1],A[1,3],A[-1,-1],A[-1,2])  # Accessing individual elements, negative counts from the end
A[2,2] = 777    # Changing elements
print(A,'\n')             
A[2,2] = 1.234   # Attention! numpy won't change array type, it will change your input
print(A,'\n')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 

7 9 25 23
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12 777  14  15]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]] 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12  1 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]] 



You can have the same syntax as with range before (this takes time to get used to...):

In [28]:
print(A[1:4,1:4],'\n')  # central sub array
print(A[:3,2:],'\n')    # top right sub array
print(A[:,0:5:2],'\n')  # only even columns
print(A[::-1,:],'\n')   # reverse the rows 

[[ 7  8  9]
 [12  1 14]
 [17 18 19]] 

[[ 3  4  5]
 [ 8  9 10]
 [ 1 14 15]] 

[[ 1  3  5]
 [ 6  8 10]
 [11  1 15]
 [16 18 20]
 [21 23 25]] 

[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12  1 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]] 



**Surprise!** If you assign this to something, this acts like a "reference" instead of copy

In [29]:
B=A[1:4,1:4]
B[2][2]=999
print(B)
print(A)

[[  7   8   9]
 [ 12   1  14]
 [ 17  18 999]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12   1  14  15]
 [ 16  17  18 999  20]
 [ 21  22  23  24  25]]


you need to call the `copy()` to actually copy:

In [30]:
B=A[1:4,1:4].copy()
B[2][2]=888
print(B)
print(A)

[[  7   8   9]
 [ 12   1  14]
 [ 17  18 888]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12   1  14  15]
 [ 16  17  18 999  20]
 [ 21  22  23  24  25]]


#### **Linear Algebra** 

In [31]:
A = np.array([[1,77,3],[4,5,6],[7,8,9]])
B = np.linspace(5,30,6).reshape(3,2)
print('A:',A)
print('B:',B)
print('dot product\n',np.dot(A,B))
print('Matrix product\n',np.matmul(A,B)) #different from dot for dimensions>2
print('Inner product\n',np.inner(A,A))
print('Outer product\n',np.outer(A,B))
print('Trace\n',np.trace(A))
print('Transpose\n',A.T)
print('Matrix Power\n',np.linalg.matrix_power(A,2))
print('Inverse\n',np.linalg.inv(A))
print('Singular Value Decomposition\n',np.linalg.svd(A))
print('Determinant\n',np.linalg.det(A))
print('Eigen decomposition\n',np.linalg.eig(A))

A: [[ 1 77  3]
 [ 4  5  6]
 [ 7  8  9]]
B: [[ 5. 10.]
 [15. 20.]
 [25. 30.]]
dot product
 [[1235. 1640.]
 [ 245.  320.]
 [ 380.  500.]]
Matrix product
 [[1235. 1640.]
 [ 245.  320.]
 [ 380.  500.]]
Inner product
 [[5939  407  650]
 [ 407   77  122]
 [ 650  122  194]]
Outer product
 [[   5.   10.   15.   20.   25.   30.]
 [ 385.  770. 1155. 1540. 1925. 2310.]
 [  15.   30.   45.   60.   75.   90.]
 [  20.   40.   60.   80.  100.  120.]
 [  25.   50.   75.  100.  125.  150.]
 [  30.   60.   90.  120.  150.  180.]
 [  35.   70.  105.  140.  175.  210.]
 [  40.   80.  120.  160.  200.  240.]
 [  45.   90.  135.  180.  225.  270.]]
Trace
 15
Transpose
 [[ 1  4  7]
 [77  5  8]
 [ 3  6  9]]
Matrix Power
 [[330 486 492]
 [ 66 381  96]
 [102 651 150]]
Inverse
 [[-0.00666667 -1.48666667  0.99333333]
 [ 0.01333333 -0.02666667  0.01333333]
 [-0.00666667  1.18       -0.67333333]]
Singular Value Decomposition
 (array([[-9.91282776e-01,  1.31750591e-01, -4.90747261e-04],
       [-6.99328398e-02, -5.2

In [32]:
help(np.inner)

Help on function inner in module numpy:

inner(...)
    inner(a, b, /)
    
    Inner product of two arrays.
    
    Ordinary inner product of vectors for 1-D arrays (without complex
    conjugation), in higher dimensions a sum product over the last axes.
    
    Parameters
    ----------
    a, b : array_like
        If `a` and `b` are nonscalar, their last dimensions must match.
    
    Returns
    -------
    out : ndarray
        If `a` and `b` are both
        scalars or both 1-D arrays then a scalar is returned; otherwise
        an array is returned.
        ``out.shape = (*a.shape[:-1], *b.shape[:-1])``
    
    Raises
    ------
    ValueError
        If both `a` and `b` are nonscalar and their last dimensions have
        different sizes.
    
    See Also
    --------
    tensordot : Sum products over arbitrary axes.
    dot : Generalised matrix product, using second last dimension of `b`.
    einsum : Einstein summation convention.
    
    Notes
    -----
    For vector

### **Statistics:**

In [33]:
A = np.linspace(0,1,9)
print('A:',A)
print('sum:               ',np.sum(A))
print('product:           ',np.prod(A))
print('mean:              ',np.mean(A))
print('standard deviation:',np.std(A))
print('variance:          ',np.var(A))
print('minimum:           ',np.min(A))
print('maximum:           ',np.max(A))
print('median:            ',np.median(A))
print('index of min:      ',np.argmin(A))
print('index of max:      ',np.argmax(A))

A: [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]
sum:                4.5
product:            0.0
mean:               0.5
standard deviation: 0.3227486121839514
variance:           0.10416666666666667
minimum:            0.0
maximum:            1.0
median:             0.5
index of min:       0
index of max:       8


**"Surprise" on argmin/argmax:**

In [34]:
A=np.linspace(0,10,9).reshape(3,3)
print(np.argmax(A))

8


In [35]:
print(np.unravel_index(np.argmax(A), A.shape))

(2, 2)


#### **More traps:**

Sometimes you have to think like a c/c++ programmer:

**overflow is possible with numpy arrays**

In [36]:
arr13 = 12345678987654321*np.ones((1), dtype='int8')
arr14 = np.array([12345678987654321], dtype='int8')
print(arr13)
print(arr14)

OverflowError: Python int too large to convert to C long

If you deal with too much data/big arrays, it's a good idea to "delete" them after usage, so that they wouldn't take up memory space. Python garbage collector will take care of them then (though not instantly). You can just do:

In [37]:
arr1=None
print(arr1)

None


Help becomes too complicated with too many functions. You can use:

In [38]:
np.lookfor("exponent")

Search results for 'exponent'
-----------------------------
numpy.exp
    Calculate the exponential of all elements in the input array.
numpy.frexp
    Decompose the elements of x into mantissa and twos exponent.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.ma.exp
    Calculate the exponential of all elements in the input array.
numpy.random.Generator.exponential
    Draw samples from an exponential distribution.
numpy.random.Generator.laplace
    Draw samples from the Laplace or double exponential distribution with
numpy.random.RandomState.exponential
    Draw samples from an exponential distribution.
numpy.random.RandomState.laplace
    Draw samples from the Laplace or double exponential distribution with
numpy.log
    Natural logarithm, element-wise.
numpy.expm1
    Calculate ``exp(x) - 1`` for all elements in the array.
numpy.finfo
    finfo(dtype)
numpy.ldexp
 

Why use numpy arrays over normal?

In [39]:
A=np.array(range(0,900)).reshape(30,30)
B=np.array(range(34,934)).reshape(30,30)

In [40]:
%%timeit
np.matmul(A,B)

47.6 µs ± 1.42 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [41]:
A=[[x for x in range(30)] for i in range(30)]
B=[[x+34 for x in range(30)] for i in range(30)]

In [42]:
%%timeit
np.matmul(A,B)

280 µs ± 5.13 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


#### **Is numpy fast?**

Yes, when you know what you are doing.

Unfortunately, it's very easy to write bad code in python, much easier than in c/c++...

Let's look at the exercise1 from the last lecture (see solutions1.ipynb)

### **Matplotlib**

this section was taken from [here](https://github.com/JamesFergusson/Research-Computing/)

In [ ]:
from matplotlib import pyplot as plt

Let's do the first simple plot:

In [ ]:
x = np.linspace(0,10,100)
y = np.sin(x)
plt.plot(x,y)

We can do muplitple at once:

In [ ]:
y1 = np.sin(x)
y2 = np.cos(x)
plt.plot(x,y1)
plt.plot(x,y2) 

We can play with the line colors and styles:

In [ ]:
x = np.linspace(0,5,20)
y1 = np.sin(x)
y2 = np.sin(x) + 0.2
y3 = np.sin(x) + 0.4
y4 = np.sin(x) + 0.6
y5 = np.sin(x) + 0.8
y6 = np.sin(x) + 1
plt.plot(x,y1,linestyle='-',linewidth=1,color='r',marker=('o'))
plt.plot(x,y2,linestyle='--',linewidth=2,color='#64D081',marker=('^'))
plt.plot(x,y3,linestyle='-.',linewidth=3,color=(139/255, 0, 139/255),marker=('s'))
plt.plot(x,y4,linestyle=':',linewidth=4,color='lime',marker=('*'))
plt.plot(x,y5,linestyle=' ',marker=('$HI$'),color='steelblue')

In [ ]:
x = np.linspace(0,5,20)
y1 = np.sin(x)
y2 = np.sin(x) + 0.2
y3 = np.sin(x) + 0.4
y4 = np.sin(x) + 0.6
y5 = np.sin(x) + 0.8
y6 = np.sin(x) + 1

#aspect ratio
w, h = plt.figaspect(0.36)
plt.figure('Sin plots',figsize=(w,h))

plt.plot(x,y1,linestyle='-',linewidth=1,color='r',marker=('o'))
plt.plot(x,y2,linestyle='--',linewidth=2,color='#00FA9A',marker=('^'))
plt.plot(x,y3,linestyle='-.',linewidth=3,color=(139/255, 0, 139/255),marker=('s'))
plt.plot(x,y4,linestyle=':',linewidth=4,color='lightcoral',marker=('*'))
plt.plot(x,y5,linestyle=' ',marker=('$H$'),color='steelblue')

# Tick location and limits
plt.xticks((0,1,2,3,4,5))
plt.xlim(0,5)
plt.yticks((-1,0,1,2))
plt.ylim(-1,2)

# Make ticks point inwards and also appear top and right
plt.tick_params(direction='in',top=True,right=True)

#Add some labels
plt.title('Plot of some stuff',fontsize = 'xx-large',fontstyle='italic',fontweight = 'light')
plt.ylabel('This is the $y$ axis',fontsize = 'xx-large',fontstyle='oblique',fontweight = 'heavy')
plt.xlabel('This is the $x$ axis',fontsize = 'xx-large',fontstyle='normal',fontweight = 'medium')

# add a legend, annoyingly here you can't use most font commands but have to set it manually and import as 'prop'
# you can also label the lines in the plot diective with: label='name here'
import matplotlib.font_manager as font_manager
font = font_manager.FontProperties(weight='bold',style='normal', size=16)
plt.legend(('A','B','C','D','E'),prop=font,loc='upper right', shadow=True)

# removed extra white space
plt.tight_layout()

There is a different interface to do exactly the same. You can choose whatever way you prefer, but the below one is better for multiple plots:

In [ ]:
x = np.linspace(0,5,20)
y1 = np.sin(x)
y2 = np.sin(x) + 0.2
y3 = np.sin(x) + 0.4
y4 = np.sin(x) + 0.6
y5 = np.sin(x) + 0.8
y6 = np.sin(x) + 1

#aspect ratio
w, h = plt.figaspect(0.36)
fig = plt.figure('Sin plots',figsize=(w,h))
ax = plt.axes()

ax.plot(x,y1,linestyle='-',linewidth=1,color='r',marker=('o'))
ax.plot(x,y2,linestyle='--',linewidth=2,color='#00FA9A',marker=('^'))
ax.plot(x,y3,linestyle='-.',linewidth=3,color=(139/255, 0, 139/255),marker=('s'))
ax.plot(x,y4,linestyle=':',linewidth=4,color='lightcoral',marker=('*'))
ax.plot(x,y5,linestyle=' ',marker=('$H$'),color='steelblue')

# Tick location and limits
ax.set(xticks=(0,1,2,3,4,5),xlim=(0,5),yticks=(-1,0,1,2),ylim=(-1,2))

# Make ticks point inwards and also appear top and right
ax.tick_params(direction='in',top=True,right=True)

# Add some labels
ax.set_title('Plot of some stuff',fontsize = 'xx-large',fontstyle='italic',fontweight = 'light')
ax.set_ylabel('This is the $y$ axis',fontsize = 'xx-large',fontstyle='oblique',fontweight = 'heavy')
ax.set_xlabel('This is the $x$ axis',fontsize = 'xx-large',fontstyle='normal',fontweight = 'medium')

# add a legend, annoyingly here you can't use most font commands but have to set it manually and import as 'prop'
import matplotlib.font_manager as font_manager
font = font_manager.FontProperties(weight='bold',style='normal', size=16)
ax.legend(('A','B','C','D','E'),prop=font,loc='upper right', shadow=True)

# removed extra white space
plt.tight_layout()

In [ ]:
x = np.linspace(0,5,20)
y1 = np.sin(x)
y2 = np.sin(x + 0.2)
y3 = np.sin(x + 0.4)
y4 = np.sin(x + 0.6)
y5 = np.sin(x + 0.8)
y6 = np.sin(x + 1)

# now we decide the actual figure size in inches
fig = plt.figure(figsize=(12,6))

# create subplots 231 means make a 2x3 grid and this is the first plot
plt.subplot(231)
plt.plot(x,y1,color='r')
plt.subplot(232)
plt.plot(x,y2,color='g')
plt.subplot(233)
plt.plot(x,y3,color='b')
plt.subplot(234)
plt.plot(x,y4,color='y')
plt.subplot(235)
plt.plot(x,y5,color='c')
plt.subplot(236)
plt.plot(x,y6,color='m')
# removed extra white space
plt.tight_layout()


In [ ]:
# now we decide the actual figure and share x and y axes
fig, ax = plt.subplots(2,3,figsize=(12,6), sharex=True,sharey=True)

# Now each plot has a location defined by the numpy array ax
ax[0,0].plot(x,y1,color='r')
ax[0,1].plot(x,y2,color='g')
ax[0,2].plot(x,y3,color='b')
ax[1,0].plot(x,y4,color='y')
ax[1,1].plot(x,y5,color='c')
ax[1,2].plot(x,y6,color='m')
# removed extra white space
fig.tight_layout()

We can make multiple plots of different sizes by creating 2 sets of subplots which are multiples of each other using the same method 

In [ ]:
x = np.linspace(0,5,20)
y1 = np.sin(x)
y2 = np.sin(x + 0.2)
y3 = np.sin(x + 0.4)
y4 = np.sin(x + 0.6)
y5 = np.sin(x + 0.8)
y6 = np.sin(x + 1.0)
y7 = np.sin(x + 1.2)

# now we decide the actual figure size in inches
fig = plt.figure(figsize=(12,6))

# create subplots now we have created a 2x2 grid and a 4x4 grid and fitted them together
plt.subplot(221)
plt.plot(x,y1,color='r')
plt.subplot(223)
plt.plot(x,y2,color='g')
plt.subplot(224)
plt.plot(x,y7,color='k')

plt.subplot(443)
plt.plot(x,y3,color='b')
plt.subplot(444)
plt.plot(x,y4,color='y')
plt.subplot(447)
plt.plot(x,y5,color='c')
plt.subplot(448)
plt.plot(x,y6,color='m')

different way to do the same:

In [ ]:
x = np.linspace(0,5,20)
y1 = np.sin(x)
y2 = np.sin(x + 0.2)
y3 = np.sin(x + 0.4)
y4 = np.sin(x + 0.6)
y5 = np.sin(x + 0.8)
y6 = np.sin(x + 1.0)
y7 = np.sin(x + 1.2)

# create figure
fig = plt.figure(figsize=(12,6))
# import gridspec and create a 4x4 grid
# we can also specifc the ratios of the sections of the grid relative to each other
import matplotlib.gridspec as gs
grid = gs.GridSpec(4, 4,width_ratios=[1,1,1,2],height_ratios=[1,1,1,1])

# Create axis objects for each plot
ax1 = plt.subplot(grid[0:2,0:2])
ax2 = plt.subplot(grid[2:4,0:2])
ax3 = plt.subplot(grid[2:4,2:4])
ax4 = plt.subplot(grid[0,2])
ax5 = plt.subplot(grid[0,3])
ax6 = plt.subplot(grid[1,2])
ax7 = plt.subplot(grid[1,3])

# create subplots
ax1.plot(x,y1,color='r')
ax2.plot(x,y2,color='g')
ax3.plot(x,y7,color='k')

ax4.plot(x,y3,color='b')
ax5.plot(x,y4,color='y')
ax6.plot(x,y5,color='c')
ax7.plot(x,y6,color='m')

If we go back to the previous example of 6 plots in a regular grid we can do it with gridspec which gives us more control:

In [ ]:
# create figure
fig = plt.figure(figsize=(12,6))
# import gridspec and create a 4x4 grid
# This time lets join them up into one
import matplotlib.gridspec as gs
grid = gs.GridSpec(2,3,wspace=0,hspace=0)

# Create axis objects for each plot
ax1 = plt.subplot(grid[0,0])
ax2 = plt.subplot(grid[0,1])
ax3 = plt.subplot(grid[0,2])
ax4 = plt.subplot(grid[1,0])
ax5 = plt.subplot(grid[1,1])
ax6 = plt.subplot(grid[1,2])

# create subplots for all 6
ax1.plot(x,y1,color='r')
ax2.plot(x,y2,color='g')
ax3.plot(x,y7,color='b')
ax4.plot(x,y3,color='y')
ax5.plot(x,y4,color='c')
ax6.plot(x,y5,color='m')

# Turn the ticks inward
ax1.tick_params(direction='in',top=True,right=True)
ax2.tick_params(direction='in',top=True,right=True)
ax3.tick_params(direction='in',top=True,right=True)
ax4.tick_params(direction='in',top=True,right=True)
ax5.tick_params(direction='in',top=True,right=True)
ax6.tick_params(direction='in',top=True,right=True)

# set the limits to be the same so they line up perfectly
ax1.set(xlim=(0,5),ylim=(-1.05,1.05))
ax2.set(xlim=(0,5),ylim=(-1.05,1.05))
ax3.set(xlim=(0,5),ylim=(-1.05,1.05))
ax4.set(xlim=(0,5),ylim=(-1.05,1.05))
ax5.set(xlim=(0,5),ylim=(-1.05,1.05))
ax6.set(xlim=(0,5),ylim=(-1.05,1.05))

# Add grids
ax1.grid(True)
ax2.grid(True)
ax3.grid(True)
ax4.grid(True)
ax5.grid(True)
ax6.grid(True)

# remove tick labels for interior axes
ax1.xaxis.set(ticklabels=[])
ax2.xaxis.set(ticklabels=[])
ax3.xaxis.set(ticklabels=[])

ax2.yaxis.set(ticklabels=[])
ax3.yaxis.set(ticklabels=[])
ax5.yaxis.set(ticklabels=[])
ax6.yaxis.set(ticklabels=[])


More plot examples (so that you could have nice styles when you need them):

In [ ]:
x = np.linspace(0,5,30)
y1 = np.sin(x)
y2 = np.cos(x)
e1 = 0.1*np.random.randn(len(x))
e2 = 0.2*np.random.randn(len(x))
h1 = 100 + 20*np.random.randn(10000)
y5 = np.sin(x + 0.8)
y6 = np.sin(x + 1.0)
y7 = np.sin(x + 1.2)

# create figure
fig = plt.figure(figsize=(15,6))
# import gridspec and create a 4x4 grid
# This time lets join them up into one
import matplotlib.gridspec as gs
grid = gs.GridSpec(2,4)

# Create axis objects for each plot
ax1 = plt.subplot(grid[0,0])
ax2 = plt.subplot(grid[0,1])
ax3 = plt.subplot(grid[0,2])
ax4 = plt.subplot(grid[0,3])
ax5 = plt.subplot(grid[1,0])
ax6 = plt.subplot(grid[1,1])
ax7 = plt.subplot(grid[1,2], projection='polar')
ax8 = plt.subplot(grid[1,3])

ax1.fill_between(x,y1,y2)
ax2.errorbar(x,y1,fmt='.k',xerr=e1,yerr=e2,linestyle=' ')
ax3.loglog(x,y1)
ax4.hist(h1,50)
ax5.scatter(e1,e2,c=e1)
ax6.pie(np.abs(y1))
ax7.plot(x,y1)
ax8.plot(x,y1)

ax8.text(1.3,0.6,'some text')

**Different plot styles:**

In [ ]:
with plt.style.context(('dark_background')):
    plt.plot(x,y5,color='m')

In [ ]:
with plt.style.context(('classic')):
    plt.plot(x,y1,color='r')

In [ ]:
with plt.style.context(('ggplot')):
    plt.plot(x,y2,color='g')

In [ ]:
with plt.style.context(('grayscale')):
    plt.plot(x,y2,color='c')

In [ ]:
with plt.style.context(('seaborn')):
    plt.plot(x,y7,color='b')

In [ ]:
with plt.style.context(('seaborn-white')):
    plt.plot(x,y2,color='y')

### **For very nice looking statistical data, use this [package](https://seaborn.pydata.org/)**

### **3D plots**

In [ ]:
from mpl_toolkits import mplot3d

x = np.linspace(0,20,100)
y = x*np.sin(x)
z = x*np.cos(x)

fig = plt.figure(figsize=(10,10))
ax = plt.axes(projection='3d')

ax.plot3D(x,y,z)

In [ ]:
x = np.linspace(0,20,100)
y = x*np.sin(x)
z = x*np.cos(x)

fig = plt.figure(figsize=(10,10))
ax = plt.axes(projection='3d')

ax.scatter3D(x,y,z,c=z)

In [ ]:
x = np.linspace(0,10,100)
y = x
X,Y=np.meshgrid(x,y)

Z = (X-5)**2 + (Y-5)

fig = plt.figure(figsize=(15,10))
ax = plt.axes(projection='3d')

ax.contour3D(X,Y,Z,50)

In [ ]:
u, v = np.mgrid[0:2*np.pi:100j, 0:np.pi:50j]
x = np.cos(u)*np.sin(v)
y = np.sin(u)*np.sin(v)
z = np.cos(v)

fig = plt.figure(figsize=(15,15))
ax = plt.axes(projection='3d')

ax.plot_wireframe(x, y, z)

In [ ]:
x = np.linspace(0,10,100)
y = x
X,Y=np.meshgrid(x,y)

Z = (X-5)**2 + (Y-5)

fig = plt.figure(figsize=(15,10))
ax = plt.axes(projection='3d')

ax.plot_surface(X,Y,Z,rstride=1,cstride=1,cmap='cubehelix')

In [ ]:
x = np.linspace(0,20,100)
y = np.linspace(0,2*np.pi,100)

r,t=np.meshgrid(x,y)

X = r * np.sin(t)
Y = r * np.cos(t)

Z = (X-5)**2 + (Y-5)

fig = plt.figure(figsize=(15,10))
ax = plt.axes(projection='3d')

ax.plot_surface(X,Y,Z)

In [ ]:
x = 2*np.random.random(1000)-1e0
y = 2*np.random.random(1000)-1e0

z = x**2 + y**3

fig = plt.figure(figsize=(15,10))
ax = plt.axes(projection='3d')

ax.plot_trisurf(x,y,z)